[tool.pylsp]
plugins.jedi.enabled = true
plugins.jedi.environment = "/usr/local/bin/python3"
plugins.jedi_completion.enabled = true
plugins.jedi_completion.include_params = true
plugins.jedi_completion.include_class_objects = true
plugins.jedi_completion.include_function_objects = true
plugins.jedi_definition.enabled = true
plugins.jedi_definition.follow_imports = true
plugins.jedi_definition.follow_builtin_imports = true
plugins.jedi_hover.enabled = true
plugins.jedi_references.enabled = true
plugins.jedi_signature_help.enabled = true
plugins.jedi_symbols.enabled = true
plugins.jedi_symbols.all_scopes = true
plugins.mccabe.enabled = true
plugins.mccabe.threshold = 15
plugins.preload.enabled = true
plugins.preload.modules = ["src"]
plugins.pycodestyle.enabled = true
plugins.pycodestyle.exclude = ["__pycache__"]
plugins.pycodestyle.filename = "*.py"
plugins.pycodestyle.select = []
plugins.pycodestyle.ignore = ["E501", "W503"]
plugins.pydocstyle.enabled = false
plugins.pyflakes.enabled = true
plugins.pylint.enabled = true
plugins.pylint.args = ["--disable=C0111"]
plugins.rope_completion.enabled = true
plugins.rope_rename.enabled = true
plugins.yapf.enabled = false
plugins.black.enabled = true
plugins.autopep8.enabled = false
plugins.flake8.enabled = true
plugins.flake8.maxLineLength = 88
plugins.flake8.ignore = ["E501", "W503"]
plugins.mypy.enabled = true
plugins.mypy.live_mode = true
plugins.mypy.strict = false
